export const GET_YOUTUBE_POPULAR_MUSIC = "GET_YOUTUBE_POPULAR_MUSIC";
export const GET_YOUTUBE_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const GET_LYRICS = "GET_LYRICS";
export const CLEAR_LYRICS = "CLEAR_LYRICS";
export const NOT_FOUND = "NOT_FOUND";
export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT";
export const SET_WATCHED_VIDEOS = "SET_WATCHED_VIDEOS";
export const ADD_MORE_JOKES = "ADD_MORE_JOKES";
